import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 40
decorations = "Transparent"
opacity = 0.90
blur = true
option_as_alt = "None"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 18

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500


